import Head from "next/head";

import Header from "@components/header";
import Section from "@components/section/Section";
import styles from "@styles/Home.module.css";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rotate Image</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <Header />
      </header>

      <main className={styles.main}>
        <Section />
      </main>
    </div>
  );
};

export default Home;
